global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 1s

    static_configs:
      - targets: ["host.docker.internal:4466"]
        labels:
          service: reaper
          group: development
