name: "Setup Workspace"
description: "Install and pre-build tools for the workspace"
inputs:
  mise-env:
    description: The environment type to install MISE tools for
    default: "prod"
    required: true
  storm-bot-private-key:
    description: The private key of the Storm bot
    required: true
  storm-bot-passphrase:
    description: The passphrase of the Storm bot
    required: true

runs:
  using: composite
  steps:
    - name: Setup GPG
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ inputs.storm-bot-private-key }}
        passphrase: ${{ inputs.storm-bot-passphrase }}

    - name: Setup MISE
      run: |
        curl https://mise.run | sh
        mise install
      env:
        MISE_ENV: ${{ inputs.mise-env }}
        MISE_USE_TOML: 1
      shell: bash

    # - name: Install Zig toolchain
    #   uses: korandoru/setup-zig@v1
    #   with:
    #     zig-version: 0.13.0

    - name: Install Cargo Lambda
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with:
        repo: cargo-lambda/cargo-lambda
        # Note: make sure you are using a recent version of cargo-lambda (the one below isn't kept in sync with new releases)
        tag: v1.3.0 # Remove this if you want to grab always the latest version
        platform: linux # Other valid options: 'windows' or 'darwin'
        # arch: aarch64 # Other valid options for linux: 'aarch64'

    - name: Restore cached npm dependencies
      id: cache-dependencies-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          node_modules
          ~/.cache/Cypress # needed for the Cypress binary
          ~/.cache/mise/${{ inputs.mise-env }}
        key: "dependencies-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('./.config/mise/config.${{ inputs.mise-env }}.toml') }}"

    - name: Set up npm registry
      uses: actions/setup-node@v4
      with:
        registry-url: https://registry.npmjs.org/
        node-version-file: .github/.nvmrc
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install pnpm package manager
      run: pnpm install --no-frozen-lockfile
      env:
        # postinstall uses this
        SHOULD_UNLOCK_GIT_CRYPT: "1"
      shell: bash

    - name: Setup pnpm config registry
      run: pnpm config set registry https://registry.npmjs.org
      shell: bash

    - name: Cache npm dependencies
      id: cache-dependencies-save
      uses: actions/cache/save@v4
      with:
        path: |
          node_modules
          ~/.cache/Cypress # needed for the Cypress binary
          ~/.cache/
        key: ${{ steps.cache-dependencies-restore.outputs.cache-primary-key }}

    - name: Configure git
      run: |
        git config user.name "Stormie-Bot"
        git config user.email "Stormie-Bot@users.noreply.github.com"
        git config lfs.allowincompletepush true
        git config --global init.defaultBranch main
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      shell: bash

    # - name: Add rust toolchain
    #   uses: dtolnay/rust-toolchain@nightly
    #   with:
    #     toolchain: nightly
    #     components: clippy,rustfmt

    # - uses: Swatinem/rust-cache@v2
    #   with:
    #     key: "cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('.tool-versions') }}"
