tab_spaces = 4
hard_tabs = false
edition = "2021"
use_small_heuristics = "Max"
use_field_init_shorthand = true
error_on_line_overflow = true
error_on_unformatted = false
trailing_semicolon = false
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
format_strings = true
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
reorder_functions = true
reorder_type_parameters = true
reorder_fields = true
reorder_struct_fields = true
reorder_variant_fields = true
reorder_impl_items = true
reorder_trait_methods = true
reorder_match_arms = true
reorder_chain = true
reorder_comments = true
reorder_blank_lines = true
reorder_empty_impl_items = true

# Nightly
max_width = 100
comment_width = 100
imports_granularity = "Crate"
merge_imports = true
chain_width = 60
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
format_macro_matchers = true
