
[workspace]
resolver = '2'
members = [
    'crates/core',
    'crates/crypto-core',
    'crates/aws',
    'apps/eth-execution-telegram-bot',
    'apps/eth-execution-engine',
]

[workspace.package]
version = '0.0.1'
description = '💵 A monorepo containing various utilities, libraries, and applications used by Storm Software in trading processes'
repository = 'https://github.com/storm-software/storm-trading'
edition = '2021'
authors = ['storm-software', 'pat-sullivan']
license = 'Apache-2.0'
documentation = 'https://stormsoftware.com/projects/storm-trading/docs'
homepage = 'https://stormsoftware.com'
categories = ['config', 'development-tools']
keywords = [
    'storm',
    'storm-trading',
    'storm-software',
    'trading',
    'cryptocurrency',
    'crypto',
    'ethereum',
    'quantitative-finance',
    'quantitative-trading',
    'quantitative-analysis',
    'quantitative-research',
    'algorithmic-trading',
    'monorepo',
]

[profile.release]
strip = false
lto = 'fat'
codegen-units = 16
panic = 'unwind'
