[book]
authors = ["Storm Software"]
language = "en"
multilingual = false
src = "src"
title = "Reaper Book"
description = "An internal Storm Software book that outlines the Reaper project."

[output.html]
theme = "src/theme"
git-repository-url = "https://github.com/storm-software/reaper"
default-theme = "coal"
no-section-label = true
mathjax-support = true

[output.html.fold]
enable = true
level = 1

[build]
build-dir = "../../dist/docs/book"

[rust]
edition = "2021"
