[env]
_.file = "../../.envrc"

[tools]
direnv = "2.34.0"
gitsign = "0.10.2"
nodejs = "20.14.0"
pnpm = "9.10.0"
lefthook = "1.6.18"
rust = "nightly-x86_64-unknown-linux-gnu"
rust-analyzer = "2024-09-02"
cargo-binstall = "1.10.3"
zig = "0.13.0"
mdbook = "0.4.14"
mdbook-linkcheck = "0.7.7"
terragrunt = "0.63.6"
opentofu = "1.8.0"
helm = "3.15.4"

[plugins]
direnv = "https://github.com/asdf-community/asdf-direnv.git"
gitsign = "https://github.com/spencergilbert/asdf-gitsign.git"
pnpm = "https://github.com/jonathanmorley/asdf-pnpm.git"
lefthook = "https://github.com/jtzero/asdf-lefthook.git"
rust = "https://github.com/code-lever/asdf-rust.git"
rust-analyzer = "https://github.com/xyven1/asdf-rust-analyzer.git"
mdbook = "https://github.com/cipherstash-archive/asdf-mdbook.git"
mdbook-linkcheck = "https://github.com/cipherstash-archive/asdf-mdbook-linkcheck.git"
helm = "https://github.com/Antiarchitect/asdf-helm.git"
opentofu = "https://github.com/virtualroot/asdf-opentofu.git"
terragrunt = "https://github.com/ohmer/asdf-terragrunt.git"

[settings]
legacy_version_file = true
always_keep_download = false
always_keep_install = false
cargo_binstall = true
plugin_autoupdate_last_check_duration = '1 week'
verbose = true
asdf_compat = false
http_timeout = 30
jobs = 4
raw = false
yes = false
not_found_auto_install = true
paranoid = false
experimental = true
status = { missing_tools = "if_other_versions_installed", show_env = true, show_tools = true }
color = true

[tasks."sign:commit"]
run = "gitsign verify --certificate-identity=patrick.joseph.sullivan@protonmail.com --certificate-oidc-issuer=https://accounts.google.com HEAD"
