[env]
RUST_BACKTRACE = 1
RUSTFLAGS = "-Z unstable-options -D warnings"
RUSTDOCFLAGS = "--cfg docsrs --show-type-layout --generate-link-to-definition --enable-index-page"
NODE_ENV = "development"
MISE_ENV = "dev"
MISE_USE_TOML = 1
NX_VERBOSE_LOGGING = 1
DEV_EDITOR_ID = "vscode"
CLICOLOR = 1
FORCE_COLOR = 1
CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG = 1

[tools]
direnv = "2.34.0"
nodejs = "20.14.0"
pnpm = "9.8.0"
lefthook = "1.6.18"
rust = "nightly-x86_64-unknown-linux-gnu"
cargo-binstall = "1.10.3"
zig = "0.13.0"
mdbook = "0.4.14"
mdbook-linkcheck = "0.7.7"
terragrunt = "0.63.6"
opentofu = "1.8.0"
helm = "3.15.4"

[settings]
legacy_version_file = true
always_keep_download = false
always_keep_install = false
cargo_binstall = true
plugin_autoupdate_last_check_duration = '1 week'
verbose = true
asdf_compat = false
http_timeout = 30
jobs = 4
raw = false
yes = false
not_found_auto_install = true
task_output = "prefix"
paranoid = false
experimental = true
status = { missing_tools = "if_other_versions_installed", show_env = true, show_tools = true }
